[project]
name = "earthquake-de-project"
version = "0.1.0"
description = "Earthquake pipeline project"
authors = [{ name = "s-yu-dev", email = "s.yukhnovets@proton.me" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = ["apache-airflow (>=3.1.3,<4.0.0)", "duckdb (>=1.4.2,<2.0.0)", "pendulum (>=3.1.0,<4.0.0)", "s3fs (>=2025.12.0,<2026.0.0)", "psycopg2-binary (>=2.9.11,<3.0.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.14.8,<0.15.0)"
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[tool.ruff.format]
quote-style = "double"